LANGUAGES = {
    'zh': {
        'title': "CAN协议上位机 - 创芯科技CANalyst-II",
        'connect': "连接",
        'disconnect': "断开",
        'start_send': "启动发送",
        'stop_send': "停止发送",
        'receive_control': "接收控制:",
        'open_receive': "开启接收",
        'send_control': "发送控制:",
        'status': "状态",
        'send': "发送",
        'receive': "接收",
        'heartbeat_status': "心跳状态",
        'stat_info': "统计信息",
        'send_data': "发送数据",
        'realtime_data': "实时数据",
        'log': "通信日志",
        'clear_log': "清空日志",
        'auto_save_log': "自动保存日志",
        'save_log': "保存日志",
        'language': "语言/Language:",
        'connection_settings': "连接设置",
        'control': "控制",
        'device_type': "设备类型:",
        'device_index': "设备索引:",
        'can_channel': "CAN通道:",
        'baud_rate': "波特率:",
        'can_id': "CAN ID",
        'parameter': "参数",
        'value': "数值",
        'unit': "单位",
        'status_col': "状态",
        'refresh_time': "刷新时间",
        'send_status': "发送状态",
        'send_count': "发送次数",
        'send_time': "发送时间",
        'stop_send': "停止发送",
        'start_send_status': "正在发送",
        'stopped': "已停止",
        'normal': "正常",
        'waiting': "等待",
        'stop': "停止",
        'yes': "是",
        'no': "否",
        'disconnected': "未连接",
        'connected': "已连接",
        # 表格项（仅示例，需补全所有项）
        
        'table_351': [
            ('心跳状态', 'heartbeat_status'),
            ('充电电压限制', 'charge_voltage_limit'),
            ('最大充电电流', 'max_charge_current'),
            ('最大放电电流', 'max_discharge_current'),
            ('放电电压', 'discharge_voltage'),
        ],
        'table_355': [
            ('SOC值', 'soc_value'),
            ('SOH值', 'soh_value'),
            ('高精度SOC', 'high_res_soc'),
        ],
        'table_356': [
            ('电池电压', 'battery_voltage'),
            ('电池电流', 'battery_current'),
            ('电池温度', 'battery_temperature'),
        ],
        'table_35A_alarm': [
            ('总报警', 'general_alarm'),
            ('电池高压报警', 'battery_high_voltage_alarm'),
            ('电池低压报警', 'battery_low_voltage_alarm'),
            ('电池高温报警', 'battery_high_temp_alarm'),
            ('电池低温报警', 'battery_low_temp_alarm'),
            ('电池高温充电报警', 'battery_high_temp_charge_alarm'),
            ('电池低温充电报警', 'battery_low_temp_charge_alarm'),
            ('电池高电流报警', 'battery_high_current_alarm'),
            ('电池高充电电流报警', 'battery_high_charge_current_alarm'),
            ('接触器报警', 'contactor_alarm'),
            ('短路报警', 'short_circuit_alarm'),
            ('BMS内部报警', 'bms_internal_alarm'),
            ('电池不平衡报警', 'cell_imbalance_alarm'),
        ],
        'table_35A_warning': [
            ('总警告', 'general_warning'),
            ('电池高压警告', 'battery_high_voltage'),
            ('电池低压警告', 'battery_low_voltage'),
            ('电池高温警告', 'battery_high_temp'),
            ('电池低温警告', 'battery_low_temp'),
            ('电池高温充电警告', 'battery_high_temp_charge'),
            ('电池低温充电警告', 'battery_low_temp_charge'),
            ('电池高电流警告', 'battery_high_current'),
            ('电池高充电电流警告', 'battery_high_charge_current'),
            ('接触器警告', 'contactor_warning'),
            ('短路警告', 'short_circuit_warning'),
            ('BMS内部警告', 'bms_internal'),
            ('电池不平衡警告', 'cell_imbalance'),
            ('系统状态', 'system_online'),
        ],
        'table_35E':[
            ('厂商名称','Manufacturer_name')
        ],
        'table_35F':[
            ('电池模型','Battery_Model'),
            ('固件版本','Firmware_version'),
            ('在线容量','Online_capacity_in_Ah'),
        ],
        'table_200': [
            ('运行模式', 'operation_mode'),
            ('SOC', 'state_of_charge'),
            ('加热器', 'Heater'),
            ('MCB状态', 'MCB status'),
            ('Top Up', 'Top Up'),
            ('Soft Start', 'Soft Start'),
            ('OCC Recovery', 'OCC Recovery'),
            ('COTC', 'COTC'),
            ('CUTC', 'CUTC'),
            ('CUTD', 'CUTD'),
            ('System Lock', 'System Lock'),
            ('SCD', 'SCD'),
            ('MOT', 'MOT'),
            ('DCDC_OT', 'DCDC_OT'),
            ('CMC', 'CMC'),
            ('BVP', 'BVP'),
            ('CTD', 'CTD'),
            ('MCB_TRIP', 'MCB_TRIP'),
            ('UCM', 'UCM'),
            ('WDT', 'WDT'),
            ('U_SOC', 'U_SOC'),
            ('CUVC', 'CUVC'),
            ('CUV', 'CUV'),
            ('COV', 'COV'),
            ('OCC', 'OCC'),
            ('OCD', 'OCD'),
            ('DCDC_CC', 'DCDC_CC'),
        ],
        'table_200_base': [
            ('运行模式', 'operation_mode'),
            ('SOC', 'state_of_charge'),
        ],
        'table_200_status':[
            ('加热器', 'Heater'),
            ('MCB状态', 'MCB status'),
            ('Top Up', 'Top Up'),
            ('Soft Start', 'Soft Start'),
            ('OCC Recovery', 'OCC Recovery'),
        ],
        'table_200_alarms':[
            ('COTC', 'COTC'),
            ('CUTC', 'CUTC'),
            ('CUTD', 'CUTD'),
            ('System Lock', 'System Lock'),
            ('SCD', 'SCD'),
            ('MOT', 'MOT'),
            ('DCDC_OT', 'DCDC_OT'),
            ('CMC', 'CMC'),
            ('BVP', 'BVP'),
            ('CTD', 'CTD'),
            ('MCB_TRIP', 'MCB_TRIP'),
            ('UCM', 'UCM'),
            ('WDT', 'WDT'),
            ('U_SOC', 'U_SOC'),
            ('CUVC', 'CUVC'),
            ('CUV', 'CUV'),
            ('COV', 'COV'),
            ('OCC', 'OCC'),
            ('OCD', 'OCD'),
            ('DCDC_CC', 'DCDC_CC'),
        ],
        'table_210': [
            ('电池电流', 'battery_current'),
            ('电池电压', 'battery_voltage'),
            ('轨电压', 'rail_voltage'),
            ('MOS管温度', 'fet_temperature'),    
        ],
        'table_220': [
            ('电芯电压1', 'cell_voltage_1'),
            ('电芯电压2', 'cell_voltage_2'),
            ('电芯电压3', 'cell_voltage_3'),
            ('电芯电压4', 'cell_voltage_4'),    
        ],
        'table_230': [
            ('电芯电压5', 'cell_voltage_5'),
            ('电芯电压6', 'cell_voltage_6'),
            ('电芯电压7', 'cell_voltage_7'),
            ('电芯电压8', 'cell_voltage_8'),    
        ],
        'table_240': [
            ('电芯电压9', 'cell_voltage_9'),
            ('电芯电压10', 'cell_voltage_10'),
            ('电芯电压11', 'cell_voltage_11'),
            ('电芯电压12', 'cell_voltage_12'),    
        ],
        'table_250': [
            ('电芯电压13', 'cell_voltage_13'),
            ('电芯电压14', 'cell_voltage_14'),
            ('电芯电压15', 'cell_voltage_15'),
            ('电芯电压16', 'cell_voltage_16'),    
        ],
        'table_260': [
            ('电芯温度1', 'cell_temperature_1'),
            ('电芯温度2', 'cell_temperature_2'),
            ('电芯温度3', 'cell_temperature_3'),
            ('电芯温度4', 'cell_temperature_4'),    
        ],
        'table_270': [
            ('ARM防盗模式', 'Arm_Antitheft_mode'),
            ('外部输出', 'external_output'),  
        ],
        'table_400': [
            ('DCDC温度', 'dcdc_temperature_deci_celsius'),
            ('正极端子温度', 'pos_terminal_temp_deci_celsius'),
            ('负极端子温度', 'neg_terminal_temp_deci_celsius'),
        ],
        'table_410': [
            ('电池包负极温度1', 'neg_bat_temp_1_deci_celsius'),
            ('电池包负极温度2', 'neg_bat_temp_2_deci_celsius'),
            ('电池包正极温度', 'pos_bat_temp_cb_deci_celsius'),
        ],
        'table_420': [
            ('SOH', 'state_of_health'),
            ('循环次数', 'cycle_count'),
            ('生命时间', 'lifetime_hour'),
            ('电芯平衡状态', 'cell_balance_state'),
        ],
        'table_430': [
            ('MCU运行时间', 'mcu_uptime_seconds'),
            ('MCU温度', 'mcu_temperature_deci_celsius'),
            ('AFE温度', 'afe_temperature_deci_celsius'),
        ],
        'table_440': [
            ('esp32运行时间', 'esp32_uptime_seconds'),
            ('esp32可用堆大小', 'esp32_free_heap_size_byte'),
            ('esp32温度', 'esp32_temperature_celsius'),
        ],
        'table_450': [
            ('控制器版本前8CHAR', 'controller_version_part1'),
        ],
        'table_460': [
            ('控制器版本后8CHAR', 'controller_version_part2'),
        ],
        'table_470': [
            ('BMS版本前8CHAR', 'bms_version_part1'),
        ],
        'table_480': [
            ('BMS版本后8CHAR', 'bms_version_part2'),
        ],
        'table_490': [
            ('x轴加速度', 'accelerometer_x'),
            ('y轴加速度', 'accelerometer_y'),
            ('z轴加速度', 'accelerometer_z'),
        ],
        'table_4A0': [
            ('ESP32MAC地址', 'esp32_mac_address'),
            ('模块ID', 'module_id'),
        ],
    },
    'en': {
        'title': "CAN Host Computer - CANalyst-II",
        'connect': "Connect",
        'disconnect': "Disconnect",
        'start_send': "Start Send",
        'stop_send': "Stop Send",
        'receive_control': "Receive Control:",
        'open_receive': "Enable Receive",
        'send_control': "Send Control:",
        'status': "Status",
        'send': "Send",
        'receive': "Receive",
        'heartbeat_status': "Heartbeat",
        'stat_info': "Statistics",
        'send_data': "Send Data",
        'realtime_data': "Realtime Data",
        'log': "Communication Log",
        'clear_log': "Clear Log",
        'auto_save_log': "Auto Save Log",
        'save_log': "Save Log",
        'language': "Language:",
        'connection_settings': "Connection Settings",
        'control': "Control",
        'device_type': "Device Type:",
        'device_index': "Device Index:",
        'can_channel': "CAN Channel:",
        'baud_rate': "Baud Rate:",
        'can_id': "CAN ID",
        'parameter': "Parameter",
        'value': "Value",
        'unit': "Unit",
        'status_col': "Status",
        'refresh_time': "Refresh Time",
        'send_status': "Send Status",
        'send_count': "Send Count",
        'send_time': "Send Time",
        'stop_send': "Stop Send",
        'start_send_status': "Sending",
        'stopped': "Stopped",
        'normal': "Normal",
        'waiting': "Waiting",
        'stop': "Stop",
        'yes': "Yes",
        'no': "No",
        'disconnected': "Disconnected",
        'connected': "Connected",
        # 表格项（仅示例，需补全所有项）
        'table_351': [
            ('Heartbeat', 'heartbeat_status'),
            ('Charge Voltage Limit', 'charge_voltage_limit'),
            ('Max Charge Current', 'max_charge_current'),
            ('Max Discharge Current', 'max_discharge_current'),
            ('Discharge Voltage', 'discharge_voltage'),
        ],
        'table_355': [
            ('SOC Value', 'soc_value'),
            ('SOH Value', 'soh_value'),
            ('High Precision SOC', 'high_res_soc'),
        ],
        'table_356': [  
            ('Battery Voltage', 'battery_voltage'), 
            ('Battery Current', 'battery_current'),
            ('Battery Temperature', 'battery_temperature'),
        ],
        'table_35A_alarm': [
            ('General Alarm', 'general_alarm'),
            ('Battery High Voltage Alarm', 'battery_high_voltage_alarm'),
            ('Battery Low Voltage Alarm', 'battery_low_voltage_alarm'),
            ('Battery High Temp Alarm', 'battery_high_temp_alarm'),
            ('Battery Low Temp Alarm', 'battery_low_temp_alarm'),
            ('Battery High Temp Charge Alarm', 'battery_high_temp_charge_alarm'),
            ('Battery Low Temp Charge Alarm', 'battery_low_temp_charge_alarm'),
            ('Battery High Current Alarm', 'battery_high_current_alarm'),
            ('Battery High Charge Current Alarm', 'battery_high_charge_current_alarm'),
            ('Contactor Alarm', 'contactor_alarm'),
            ('Short Circuit Alarm', 'short_circuit_alarm'),
            ('BMS Internal Alarm', 'bms_internal_alarm'),
            ('Cell Imbalance Alarm', 'cell_imbalance_alarm'),
        ],
        'table_35A_warning': [
            ('General Warning', 'general_warning'),
            ('Battery High Voltage Warning', 'battery_high_voltage'),
            ('Battery Low Voltage Warning', 'battery_low_voltage'),
            ('Battery High Temp Warning', 'battery_high_temp'),
            ('Battery Low Temp Warning', 'battery_low_temp'),
            ('Battery High Temp Charge Warning', 'battery_high_temp_charge'),
            ('Battery Low Temp Charge Warning', 'battery_low_temp_charge'),
            ('Battery High Current Warning', 'battery_high_current'),
            ('Battery High Charge Current Warning', 'battery_high_charge_current'),
            ('Contactor Warning', 'contactor_warning'),
            ('Short Circuit Warning', 'short_circuit_warning'),
            ('BMS Internal Warning', 'bms_internal'),
            ('Cell Imbalance Warning', 'cell_imbalance'),
            ('System Status', 'system_online'),
        ],
        'table_35E':[
            ('Manufacturer_name','Manufacturer_name')
        ],
        'table_35F':[
            ('Battery_Model','Battery_Model'),
            ('Firmware_version','Firmware_version'),
            ('Online_capacity_in_Ah','Online_capacity_in_Ah'),
        ],
        'table_200': [
            ('operation_mode', 'operation_mode'),
            ('SOC', 'state_of_charge'),
            ('Heater', 'Heater'),
            ('MCB status', 'MCB status'),
            ('Top Up', 'Top Up'),
            ('Soft Start', 'Soft Start'),
            ('OCC Recovery', 'OCC Recovery'),
            ('COTC', 'COTC'),
            ('CUTC', 'CUTC'),
            ('CUTD', 'CUTD'),
            ('System Lock', 'System Lock'),
            ('SCD', 'SCD'),
            ('MOT', 'MOT'),
            ('DCDC_OT', 'DCDC_OT'),
            ('CMC', 'CMC'),
            ('BVP', 'BVP'),
            ('CTD', 'CTD'),
            ('MCB_TRIP', 'MCB_TRIP'),
            ('UCM', 'UCM'),
            ('WDT', 'WDT'),
            ('U_SOC', 'U_SOC'),
            ('CUVC', 'CUVC'),
            ('CUV', 'CUV'),
            ('COV', 'COV'),
            ('OCC', 'OCC'),
            ('OCD', 'OCD'),
            ('DCDC_CC', 'DCDC_CC'),
        ],
        'table_200_base': [
            ('operation_mode', 'operation_mode'),
            ('SOC', 'state_of_charge'),
        ],
        'table_200_status':[
            ('Heater', 'Heater'),
            ('MCB status', 'MCB status'),
            ('Top Up', 'Top Up'),
            ('Soft Start', 'Soft Start'),
            ('OCC Recovery', 'OCC Recovery'),
        ],
        'table_200_alarms':[
            ('COTC', 'COTC'),
            ('CUTC', 'CUTC'),
            ('CUTD', 'CUTD'),
            ('System Lock', 'System Lock'),
            ('SCD', 'SCD'),
            ('MOT', 'MOT'),
            ('DCDC_OT', 'DCDC_OT'),
            ('CMC', 'CMC'),
            ('BVP', 'BVP'),
            ('CTD', 'CTD'),
            ('MCB_TRIP', 'MCB_TRIP'),
            ('UCM', 'UCM'),
            ('WDT', 'WDT'),
            ('U_SOC', 'U_SOC'),
            ('CUVC', 'CUVC'),
            ('CUV', 'CUV'),
            ('COV', 'COV'),
            ('OCC', 'OCC'),
            ('OCD', 'OCD'),
            ('DCDC_CC', 'DCDC_CC'),
        ],
        'table_210': [
            ('battery_current', 'battery_current'),
            ('battery_voltage', 'battery_voltage'),
            ('rail_voltage', 'rail_voltage'),
            ('fet_temperature', 'fet_temperature'),    
        ],

        'table_210': [
            ('battery_current', 'battery_current'),
            ('battery_voltage', 'battery_voltage'),
            ('rail_voltage', 'rail_voltage'),
            ('fet_temperature', 'fet_temperature'),    
        ],
        'table_220': [
            ('cell_voltage_1', 'cell_voltage_1'),
            ('cell_voltage_2', 'cell_voltage_2'),
            ('cell_voltage_3', 'cell_voltage_3'),
            ('cell_voltage_4', 'cell_voltage_4'),    
        ],
        'table_230': [
            ('cell_voltage_5', 'cell_voltage_5'),
            ('cell_voltage_6', 'cell_voltage_6'),
            ('cell_voltage_7', 'cell_voltage_7'),
            ('cell_voltage_8', 'cell_voltage_8'),    
        ],
        'table_240': [
            ('cell_voltage_9', 'cell_voltage_9'),
            ('cell_voltage_10', 'cell_voltage_10'),
            ('cell_voltage_11', 'cell_voltage_11'),
            ('cell_voltage_12', 'cell_voltage_12'),    
        ],
        'table_250': [
            ('cell_voltage_13', 'cell_voltage_13'),
            ('cell_voltage_14', 'cell_voltage_14'),
            ('cell_voltage_15', 'cell_voltage_15'),
            ('cell_voltage_16', 'cell_voltage_16'),    
        ],
        'table_260': [
            ('cell_temperature_1', 'cell_temperature_1'),
            ('cell_temperature_2', 'cell_temperature_2'),
            ('cell_temperature_3', 'cell_temperature_3'),
            ('cell_temperature_4', 'cell_temperature_4'),    
        ],
        'table_270': [
            ('Arm_Antitheft_mode', 'Arm_Antitheft_mode'),
            ('external_output', 'external_output'),  
        ],
        'table_400': [
            ('dcdc_temperature_deci_celsius', 'dcdc_temperature_deci_celsius'),
            ('pos_terminal_temp_deci_celsius', 'pos_terminal_temp_deci_celsius'),
            ('neg_terminal_temp_deci_celsius', 'neg_terminal_temp_deci_celsius'),
        ],
        'table_410': [
            ('neg_bat_temp_1_deci_celsius', 'neg_bat_temp_1_deci_celsius'),
            ('neg_bat_temp_2_deci_celsius', 'neg_bat_temp_2_deci_celsius'),
            ('pos_bat_temp_cb_deci_celsius', 'pos_bat_temp_cb_deci_celsius'),
        ],
        'table_420': [
            ('SOH', 'state_of_health'),
            ('cycle_count', 'cycle_count'),
            ('lifetime_hour', 'lifetime_hour'),
            ('cell_balance_state', 'cell_balance_state'),
        ],
        'table_430': [
            ('mcu_uptime_seconds', 'mcu_uptime_seconds'),
            ('mcu_temperature_deci_celsius', 'mcu_temperature_deci_celsius'),
            ('afe_temperature_deci_celsius', 'afe_temperature_deci_celsius'),
        ],
        'table_440': [
            ('esp32_uptime_seconds', 'esp32_uptime_seconds'),
            ('esp32_free_heap_size_byte', 'esp32_free_heap_size_byte'),
            ('esp32_temperature_celsius', 'esp32_temperature_celsius'),
        ],
        'table_450': [
            ('controller_version first 8 chars', 'controller_version_part1'),
        ],
        'table_460': [
            ('controller_version last 8 chars', 'controller_version_part2'),
        ],
        'table_470': [
            ('BMS_version_first8CHAR', 'bms_version_part1'),
        ],
        'table_480': [
            ('BMS_version_last8CHAR', 'bms_version_part2'),
        ],
        'table_490': [
            ('accelerometer_x', 'accelerometer_x'),
            ('accelerometer_y', 'accelerometer_y'),
            ('accelerometer_z', 'accelerometer_z'),
        ],
        'table_4A0': [
            ('esp32_mac_address', 'esp32_mac_address'),
            ('module_id', 'module_id'),
        ],
    }
} 